// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StrideFlow.Infrastructure.Database;

#nullable disable

namespace StrideFlow.Infrastructure.Database.Migrations
{
    [DbContext(typeof(StrideFlowDbContext))]
    partial class StrideFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StrideFlow.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<string>("CreatedByUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("created_by_user_agent");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "TokenFamilyId")
                        .HasDatabaseName("ix_refresh_tokens_user_id_token_family_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("StrideFlow.Domain.Tracking.WalkingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("CaloriesBurned")
                        .HasColumnType("double precision")
                        .HasColumnName("calories_burned");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset?>("LastPointRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_point_recorded_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<int>("PausedDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("paused_duration_seconds");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<double>("TotalDistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("total_distance_meters");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer")
                        .HasColumnName("total_steps");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_walking_sessions");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_walking_sessions_started_at");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_walking_sessions_user_id_status");

                    b.ToTable("walking_sessions", (string)null);
                });

            modelBuilder.Entity("StrideFlow.Domain.Tracking.WalkingSessionPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_meters");

                    b.Property<double>("DistanceFromPreviousMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_from_previous_meters");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<double>("SpeedMetersPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_meters_per_second");

                    b.Property<int>("StepDelta")
                        .HasColumnType("integer")
                        .HasColumnName("step_delta");

                    b.HasKey("Id")
                        .HasName("pk_walking_session_points");

                    b.HasIndex("SessionId", "RecordedAt")
                        .HasDatabaseName("ix_walking_session_points_session_id_recorded_at");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_walking_session_points_session_id_sequence");

                    b.ToTable("walking_session_points", (string)null);
                });

            modelBuilder.Entity("StrideFlow.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("accent_color");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyStepGoal")
                        .HasColumnType("integer")
                        .HasColumnName("daily_step_goal");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double precision")
                        .HasColumnName("height_cm");

                    b.Property<bool>("IsProfilePublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_profile_public");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<double>("StepLengthMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("step_length_meters");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("username");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_users_city");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StrideFlow.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("StrideFlow.Domain.Auth.RefreshToken", "ReplacedByToken")
                        .WithOne()
                        .HasForeignKey("StrideFlow.Domain.Auth.RefreshToken", "ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("StrideFlow.Domain.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrideFlow.Domain.Tracking.WalkingSession", b =>
                {
                    b.HasOne("StrideFlow.Domain.Users.User", "User")
                        .WithMany("WalkingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_walking_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrideFlow.Domain.Tracking.WalkingSessionPoint", b =>
                {
                    b.HasOne("StrideFlow.Domain.Tracking.WalkingSession", "Session")
                        .WithMany("Points")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_walking_session_points_walking_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("StrideFlow.Domain.Tracking.WalkingSession", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("StrideFlow.Domain.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("WalkingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
